baseURL = 'https://qitoy.github.io/'
languageCode = 'ja-jp'
title = "qitoy's blog"
enableGitInfo = true

[params]
author = 'しゅどぼ'
avatar = "/images/avatar.jpg"
description = 'なんだろこれ'
github = 'qitoy'
twitter = '_QiToY'
hugoRepository = 'qitoy.github.io'
url = 'https://github.com/qitoy/qitoy.github.io'

[module]
[[module.imports]]
path = "github.com/MeiK2333/github-style"
